spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.2:5432/avesmarket_ms_rri
    username: postgres
    password: 123
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser